### ISSUE TITLE
Citation and contributors

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-Hive/access-hive.github.io#147]
Spawned from #70 and #138

- [ ] Maybe add a "Contributions" tab for the contribution guidelines
- [x] Acknowledgement / citation text (SAC)

**Comment by aidanheerdegen** [comment]
ACCESS-ESM1.5 canonical reference

https://www.publish.csiro.au/es/ES19035

**Comment by ccarouge** [comment]
This says there is an acknowledgment or citation text. I can't see it. Do we need one or not?

**Comment by rbeucher** [comment]
What do you mean? There is one

**Comment by rbeucher** [comment]
![image](https://user-images.githubusercontent.com/3680918/201835901-6ac30d19-3c81-47ee-875b-f7889bd79061.png)

**Comment by ccarouge** [comment]
I don't think the citation was for a specific model. I think the original idea was to add a citation terxt for people to use when referring to material from the ACCESS-Hive, so a Hive-wide citation. Since ACCESS-Hive is only a bunch of links, it always sounded strange to me but I'm not fussed about this.

**Comment by rbeucher** [comment]
I see. I can't see how we could have that. For new content maybe but not the Hive. Anyway, let's close this.
