### ISSUE TITLE
Refine `how to contribute` guide and include best practices for creating PRs (for internal use)

### ISSUE THREAD

**Issue by KAUR1984** [ACCESS-Hive/access-hive.github.io#365]
## Description
As suggested by the team in the sprint meeting: 

- Document the steps and detailed explanation of the development workflow for Hive here - https://github.com/ACCESS-Hive/access-hive.github.io/tree/development#how-to-contribute-draft. 

- It would also be good to include that commits could still be created after creating pr's.

## Why
Although the practice of pushing commits after creating pr's is not widely encouraged, but still to let the dev team know that this functionality exists, and what best practices to follow in this scenario.

## Close Criteria
- [ ] Improve the `how to contribute` draft. 
- [ ] Include instructions of pushing commits after creating a pr.

**Comment by svenbuder** [comment]
Add to "how to contribute guide":
Make sure you start from the development branch:
git switch development
# We need to add that, because I once started creating a new branch while not being in development, and took over the changes from another branch into the new one...

How to make sure your pull request is up-to-date with the development branch?
git checkout development
git pull
git checkout dev/branch_you_want_to_update_to_latest_development
git merge development
git push

**Comment by KAUR1984** [comment]
Have the `How to contribute` section to include instructions on:

- How to pull changes from the `development` branch into the local branch regularly, to be in sync with the latest changes.

- Clarified instructions on how to make sure to start from the `development` branch to create a new branch, and not from the `main` branch (which is selected by default otherwise).

- How to contribute guide is currently on:
ACCESS-Hive readme - https://github.com/ACCESS-Hive/access-hive.github.io/blob/development/README.md.
ACCESS-Hive wiki - https://github.com/ACCESS-Hive/access-hive.github.io/wiki/2.-How-to-Contribute

**Comment by atteggiani** [comment]
Done!
Closing
